apps:
  - name: scenarioanalysis2
    ingress: enabled
    port: 3001
    image:
      build: true
      name: scenarioanalysis2
      path: ./src
      repository: default
      tag: default
      experimentalBuild: true
      compressedCache: true
      useNewRun: true
      snapshotMode: redo
    volumes: true
    volumesList:
      - name: tmp
        size: 500Mi
        type: emptyDir
        mountPath: "/tmp"
      - name: data
        size: 1Gi
        type: emptyDir
        mountPath: "/app/data"
    rewrite:
      uri: /
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 4Gi

# URI entry point to be used for launching the application
entrypoint: "https://{{ .Values.metadata.hostName }}/{{ .Values.metadata.engagementId }}/{{ $.Release.Name }}-scenarioanalysis2/"

# Secrets keys must match the ones in your Hashicorp Vault
secrets: {}

# These secrets will be injected into your enabled dependencies
dependencySecrets: []

# Runtime values will be replaced by GCaaS
metadata:
  engagementId: runtimeReplaced
  hostName: runtimeReplaced
  commitHash: runtimeReplaced

# ConfigMap values injected into containers
configMap:
  - key: NODE_ENV
    value: "\"production\""
  - key: PORT
    value: "\"3001\""

# To enable persistent logging in Datadog
persistentLogging:
  enabled: false
